version: '2.2'
services:

  php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./tests:/tests:delegated
      # Framework testing
      - ./_host-volumes/yii2:/yii2:delegated
      # Application testing
      - ./_host-volumes/app:/app:delegated
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
  mysql:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: paradam
      MYSQL_ROOT_PASSWORD: root
    volumes:
       - ./database:/var/lib/mysql
       - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
  telegram:
    build: ./docker/telegram/
    restart: always
    expose:
      - "9503"
    ports:
      - "9503:9503"
