version: '2.2'
services:

  php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./tests:/tests:delegated
      # Framework testing
      - ./_host-volumes/yii2:/yii2:delegated
      # Application testing
      - ./_host-volumes/app:/app:delegated
      # SSL
      - ./docker/nginx/ssl:/etc/nginx/ssl
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
  mysql:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paradam
      MYSQL_USER: splaa
      MYSQL_PASSWORD: splaa1977
    ports:
      - 3306:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
  telegram:
    build: ./docker/telegram/
    restart: always
    expose:
      - "9503"
    ports:
      - "9503:9503"
